import './room-details.scss';
import './../../components/head/head.js';
import './../../components/dropdown/dropdown'
import './../../components/header/header.js'
import './../../components/button/button.js'
import './../../components/footer/footer.js'
import './../../components/field-subscribe/field-subscribe.js'
import './../../components/calendar/calendar.js'
import './../../components/like-btn/like-btn.js'
import './../../components/comments/comments.js'
import './../../components/information/information.js'
import './../../components/booking/booking.js'